[global]
# atrac17 helped with the first set of MRA files
author=["jotego"]

[parse]
sourcefile=[ "sf.cpp" ]
skip.bootlegs=true
skip.setnames=[
    # graphics wrong, game boots
    "sfjan",
    # wrong inputs
    "sfan",
    # won't boot
    "sfp",
]

[buttons]
names=[
    { names="Light Punch,Middle Punch,Heavy Punch,Light Kick,Middle Kick,Heavy Kick" }
]

[dipsw]
rename=[
    {name="Game Continuation", to="Continue"},
    {name="Buy-In Feature", to="Buy in"},
    {name="Number of Countries Selected", to="Countries"},
    {name="Round Time Count", to="Time"},
]
delete=[
    { names=["Unused","Buy-In Feature"] }
]

[ROM]
regions=[
    { name="maincpu", width=16, no_offset=true },
    { name="audiocpu", start="JTFRAME_BA1_START", reverse=true },
    { name="audio2",   start="SND2_START",        reverse=true },
    { name="tilerom",  start="JTFRAME_BA2_START", width=16, sequence=[3,2,1,0]},
    { name="gfx4",     start="CHAR_START",        no_offset=true },
    { name="gfx2",     start="JTFRAME_BA3_START", width=16, sequence=[4,0,5,1,6,2,7,3], no_offset=true },
    { name="gfx1",     start="SCR2_START",        width=16, sequence=[2,0,3,1], no_offset=true },
    { name="gfx3",     start="OBJ_START",         width=16, sequence=[7,0,8,1,9,2,10,3,11,4,12,5,13,6], no_offset=true },
    { name="protcpu",  start="JTFRAME_PROM_START" },
    { name="proms", skip=true },
    { name="plds",  skip=true }
]

order=["maincpu","audiocpu", "audio2",
    "tilerom","gfx4",
    "gfx2","gfx1","gfx3", "protcpu" ]