[parse]
sourcefile=[ "wwfsstar.cpp" ]
skip.bootlegs=true

# [Audio]
# volume = [
#     { value=0x50 },
# ]

[buttons]
Names = [
    { names="Left Attack,Jump,Right Attack"},
]

# [dipsw]
# # Flip screen not supported
# delete=[{names=["Unused","Unknown"]}]
# rename = [
#     { name="Bonus Life", to="Bonus" },
# ]

[ROM]
regions=[
    { name="maincpu"  },
    { name="audiocpu",  start="JTFRAME_BA1_START"  },
    { name="oki",       start="PCM_START"          },
    { name="fgtiles",   start="JTFRAME_BA2_START"  },
    { name="bgtiles",   start="SCR_START",         width=16, no_offset=true  },
    { name="sprites",   start="JTFRAME_BA3_START", width=16, no_offset=true, sequence=[3,0,4,1,5,2]  },
]

order=[
    "maincpu", "audiocpu", "oki",
    "fgtiles", "bgtiles", "sprites",
]
