# Remember to update JTFRAME_SKIP when adding
# or removing betas
ngpc:   [ mister, pocket ]
wwfss:  [ mister, pocket ]
xmen:   [ mister, pocket ]
s18:    [ mister, pocket ]
riders: [ mister, pocket ]
circus: [ mister, pocket ]
rumble: [ pocket ]
midres: [ pocket ]

# upcoming ports from MiSTer to Pocket
# update the core's macros.def when making a new beta
# midres: [ pocket ]
# rumble: [ pocket ]
