[parse]
sourcefile=[ "ngp.cpp" ]

[ROM]
order = ["maincpu"]
firmware = "ngp.rom"
carts =[ "ngp", "ngc" ]
# bypass the settings menu:
# patches=[
# 	{ offset=0xff00, data="00 18" }
# ]
# it's better to simply power off the NGP and insert a cartridge

# skip menu patch by angel_killah
patches=[ { offset=0x1b0f,data="""00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00"""} ]

[buttons]
names = [{names="A,B,Option"}]
